name: Deploy Jupyter Book

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PUBLISH_DIR: ./docs/_build/html
      DISPLAY: ":99.0"
      # PYVISTA_TRAME_SERVER_PROXY_PREFIX: "/ibfenics/proxy/"
      # PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies for pyvista
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libglx-mesa0 mesa-utils libxrender1 xvfb

      - name: Install Jupyter Book and dependencies
        run: pip install jupyter-book pyvista panel ipyvtklink ipywidgets trame trame-vuetify trame-vtk
      
      - name: Build Jupyter Book
        run: Xvfb :99 -screen 0 1024x768x24 & cd docs && jb build .
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}